language: bash

os:
    - linux

before_install:
    - sudo apt-get update
    - sudo apt-get install curl pandoc
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
    - sudo apt-get install nodejs
    - sudo npm install --global surge

script:
    - chmod +x src/mksite
    - chmod +x src/deploy
    - cd src
    - ./mksite 123 && ./deploy
