language: bash

os:
    - linux

before_install:
    - sudo apt-get update
    - wget https://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz -O z.tar.gz
    - tar xvf z.tar.gz
    - curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
    - sudo apt-get install nodejs snapcraft
    - sudo snap install --edge zola
    - sudo npm install --global surge

script:
    - chmod +x src/deploy
    - cd src && ../zola build && ./deploy
