language: bash

os:
    - linux

before_install:
    - sudo apt-get update
    - curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
    - sudo apt-get install nodejs snapcraft
    - sudo snap refresh core
    - sudo snap install --edge zola
    - sudo npm install --global surge

script:
    - chmod +x src/deploy
    - cd src && zola build && ./deploy
