language: bash

os:
    - linux

before_install:
    - sudo apt-get update
    - sudo apt-get install nodejs zola
    - sudo npm install --global surge

script:
    - chmod +x src/deploy
    - cd src && zola build && ./deploy
