language: bash
sudo: required

os:
    - linux

before_install:
  - sudo apt-get install imagemagick pngquant jpegoptim webp
  - sudo apt-get install powershell -y

script:
    - chmod +x src/mksite
    - chmod +x src/deploy
    - src/mksite
    - src/deploy
