language: bash

os:
    - linux

before_install:
    - sudo apt-get update
    - sudo apt-get install curl webp jpegoptim pandoc golang
    - sudo apt-get install imagemagick pngquant
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
    - sudo apt-get install nodejs
    - sudo npm install --global surge
    - go get -u https://github.com/tdewolff/minify/v2

script:
    - chmod +x src/mksite
    - chmod +x src/deploy
    - cd src
    - ./mksite && ./deploy
