#!/bin/bash

site_name="<site_name>"
folders=("blah")

# --------- ADVANCED CONFIGURATION ----------
# headers - stuff to go into the <head> tag on every HTML page
headers="<link rel="stylesheet" href="http://invisi-text.surge.sh/cdn/production/0.2.0/invisi-text.min.css" />"

# footer - Stuff to go into the bottom of every page (default: empty)
footer=''

# footer_blog - Stuff to go into the bottom of every blog post (default: empty)
footer_blog='<script src="https://utteranc.es/client.js" repo="kiedtl/website" issue-term="pathname" label="comment" theme="github-light" crossorigin="anonymous" async></script>'

# homelink - the content that appears on every non-index page (default: "<a href='/'>Home</a>")
homelink="<a href='/'>Home</a>"

# homelink_blog - the content at the top of every blog post (default: "<a href='/'>Home</a> <a href='/blog/'>Blog</a>")
homelink_blog="<a href='/'>Home</a> <a href='/blog/'>Blog</a>"

# favicon - the url to your favicon. default = empty.
favicon=""

# style - the minified CSS style for your site
style='a{background:linear-gradient(to bottom,#cdcdcd,#cdcdcd) 50% calc(100% - 2px)/50% 2px no-repeat;color:#333;margin:-1px;text-decoration:none!important;-webkit-transition:all .35s ease-in-out;transition:all .35s ease-in-out}a:focus,a:hover{background-image:linear-gradient(to bottom,#777,#777);background-size:100% 3px;color:#111;-webkit-transition:all .35s ease-in-out!important;transition:all .35s ease-in-out!important}body{overflow-y:scroll;font-family:sans-serif}img,main{display:block;margin:25px auto}main{padding:20px;max-width:600px;line-height:1.6;word-wrap:break-word}img{max-width:100%}pre>code{display:block;padding:20px;white-space:pre-line}code{background:#eee;padding:2px}blockquote{border-left:7px solid #ddd;padding-left:14px;color:#666;margin:0}h1,h2,h3,h4{line-height:1.2}h1{font-family:monospace}'
