# The URL the site will be built for
base_url = "https://tilde.team/~kiedtl/"

compile_sass = false
highlight_code = false
build_search_index = false

title = "~kiedtl"
description = ""
default_language = "en"

generate_rss = true

[extra]
headers = "<meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>"

footer = "<hr><p>Kiëd Llaentenn © 2019-2021 — <a rel='license' href='http://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a></p>"

# to be alongside footer
footer_blog = "<hr><script src=\"https://utteranc.es/client.js\" repo=\"kiedtl/website\" issue-term=\"pathname\" label=\"comment\" theme=\"github-light\" crossorigin=\"anonymous\" async></script><noscript>Javascript is required for comments.</noscript>"

homelink = "<a id=\"homelink\" href='/~kiedtl/'>⟵ Back</a>"

favicon = "data:image/png;base64,"
