#!/bin/bash

newsum=$(shasum -U - <<< $(curl -sSL "https://raw.githubusercontent.com/lptstr/donsk/master/src/mksite"))
oldsum=$(shasum -U ./mksite)

printf "[donsk update] New SHA: $newsum\n"
printf "[donsk update] Old SHA: $oldsum\n"

data=$(curl -sSL "https://raw.githubusercontent.com/lptstr/donsk/master/src/mksite")

printf "[donsk update] downloading...\n"

rm -f ./mksite
echo "$data" > ./mksite
chmod +x ./mksite
printf "[donsk update] completed."
